dist: xenial
language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
cache: pip
env:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="2.2"
  - DJANGO="3.0"
  - DJANGO="3.1"
install:
- travis_retry pip install tox-travis
script:
- tox

jobs:
  exclude:
    - env: DJANGO="2.0"
      python: '2.7'
    - env: DJANGO="2.1"
      python: '2.7'
    - env: DJANGO="2.2"
      python: '2.7'
    - env: DJANGO="3.0"
      python: '2.7'
    - env: DJANGO="3.1"
      python: '2.7'

    - env: DJANGO="3.0"
      python: '3.5'
    - env: DJANGO="3.1"
      python: '3.5'

    - env: DJANGO="1.11"
      python: '3.8'
    - env: DJANGO="2.0"
      python: '3.8'
    - env: DJANGO="2.1"
      python: '3.8'

    - env: DJANGO="1.11"
      python: '3.9'
    - env: DJANGO="2.0"
      python: '3.9'
    - env: DJANGO="2.1"
      python: '3.9'

  include:
  - stage: deploy
    install: skip
    script: skip
    python: 2.7
    env: skip
    deploy:
      provider: pypi
      user: jazzband
      server: https://jazzband.co/projects/django-redshift-backend/upload
      distributions: sdist bdist_wheel
      password:
        secure: Ce8w7iTF3Cc/Tu8PPDUYtzFiSQIzjSjeFx+lPintaSJA7V/ndARWBvVLFSKghzayB5vPihDs934O0HbTsRAKHB4ChEzOiFH6u2utLkxPgqpKbmAbTRn12Xv46mwSNWV7XBnTOs8AzfqEI7y/fHDO6DT1j4FNGgyRqclH4GgsibU=
      on:
        tags: true
        repo: jazzband/django-redshift-backend
